"""Write site/data/analyzer-data.json for the Evidence Analyzer page.

The page must use the same rules and synthetic incidents as the CLI. This script
copies src/vdi_copilot/default_rules.json and every incident in
samples/incidents into one JSON document. The test suite fails when the file is
out of date; regenerate it with:

    python scripts/export_site_data.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT = ROOT / "site" / "data" / "analyzer-data.json"


def build() -> dict:
    rules = json.loads((ROOT / "src" / "vdi_copilot" / "default_rules.json").read_text("utf-8"))
    incidents = []
    for directory in sorted((ROOT / "samples" / "incidents").iterdir()):
        if not directory.is_dir():
            continue
        expected = json.loads((directory / "expected.json").read_text("utf-8"))
        files = [
            {
                "source": path.name,
                "text": path.read_text("utf-8").replace("\r\n", "\n"),
            }
            for path in sorted(directory.iterdir())
            if path.is_file() and path.name != "expected.json"
        ]
        incidents.append(
            {"id": directory.name, "expected": expected["finding_ids"], "files": files}
        )
    return {
        "description": "Generated by scripts/export_site_data.py. Do not edit by hand.",
        "rules": rules,
        "incidents": incidents,
    }


def main(argv: list[str]) -> int:
    output = Path(argv[1]) if len(argv) > 1 else DEFAULT_OUTPUT
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(
        json.dumps(build(), indent=2, ensure_ascii=False) + "\n", encoding="utf-8", newline="\n"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
